[package]
name = "egui_dev_tools"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Devtools for egui - Inspect widgets and map them back to source code"
repository = "https://github.com/membrane-io/egui_dev_tools"
authors = ["Juan Campa <juan@membrane.io>"]

[lib]
path = "src/lib.rs"

[features]
default = ["vals", "widget-inspect"]
vals = []
widget-inspect = []
logging = ["dep:egui_tracing"]

[dependencies]
egui = { workspace = true }
egui_tracing = { path = "../egui_tracing", default-features = false, features = ["log", "wasmbind"], optional = true }
egui_table = { workspace = true }
profiling = { workspace = true }
log = { workspace = true }
regex = "1"
serde = { workspace = true }
subsecond = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
backtrace = "~0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
